### ISSUE TITLE
Controller mapping doesn’t work

### ISSUE THREAD

**Issue by iCanuck** [ordovice/batocera-switch#2]
The controller mapping doesn’t work. Is this possibly from a yuzu update? I see you modified the shellscript to use an older version of yuzu now. Is there a reason for this?

**Comment by ordovice** [comment]
The newer versions of yuzu require sdl 2.0.14 which Batocera doesn’t support yet. I’ve made them aware but until then the version set for DL is the supported version for now. I’ll keep working with the bato team and yuzu teams to see if we can fix the issue but it’s unfortunately not on either of them to support this configuration at this time.

Another user has used pad2key to set up keyboard mappings (which would work for 2 player setups). I’ll add those to an optional folder later once I get a chance to review them.

Daniel Walker | JR Automation
Senior Systems Engineer
O: +1 (616) 820-3479 | C: +1 (252) 202-7719
________________________________
From: iCanuck ***@***.***>
Sent: Sunday, August 8, 2021 12:35:32 PM
To: ordovice/batocera-switch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ordovice/batocera-switch] Controller mapping doesn’t work (#2)


The controller mapping doesn’t work. Is this possibly from a yuzu update? I see you modified the shellscript to use an older version of yuzu now. Is there a reason for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fordovice%2Fbatocera-switch%2Fissues%2F2&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7C76d45f2b2fd94155afe308d95a8a8aa0%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637640373352245147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w6cVdPm8xf2gURA8ed6A8MbcURnL8WpOK7TA2jnD4HY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGNJTICWGACHFAZJPL7WFS3T32W5JANCNFSM5BYUTGIQ&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7C76d45f2b2fd94155afe308d95a8a8aa0%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637640373352255131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oHf5orxCeHT%2F5o8frt4Nezv5O5nHxHURaeSgulZpXYo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7C76d45f2b2fd94155afe308d95a8a8aa0%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637640373352255131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RGgXdBszEx2EajQebJfV4kBDxtPg6xr9NtxOzzheHjU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7C76d45f2b2fd94155afe308d95a8a8aa0%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637640373352265127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NRSPW6suWDBKNJjm0ShQBlttNFPdLvg3q%2FfLtSWfEUQ%3D&reserved=0>.

* This email was sent from an external source, please use caution and validate the email before opening attachments or clicking on hyperlinks. *

**Comment by iCanuck** [comment]
Thanks for the explanation. Makes perfect sense. thanks for all your work, i’ll try pad2key. If I find any other work arounds i’ll post it here.

**Comment by ordovice** [comment]
I'm hoping to iron out the kinks in v34 now that things are aligning for yuzu, SDL in Batocera, and my free time.

**Comment by ordovice** [comment]
Can you try out the v34 version with an updated version of yuzu now?

**Comment by ordovice** [comment]
Working with limitations, please test and open a new issue for specific controller issues
