### ISSUE TITLE
Unable to switch to Ryujinx

### ISSUE THREAD

**Issue by philsocal** [ordovice/batocera-switch#3]
Initially setup for yuzu, but my GPU only supports opengl 4.6+. Attempted to remove yuzu and install Ryujinx (as it supports opengl 4.5), but emulationstation still attempts to start yuzu-
from es_launch_stderr.log-
FileNotFoundError: [Errno 2] No such file or directory: '/userdata/system/switch/yuzu.AppImage'

in switchlauncher.py, it references yuzu on the exitCode = runCommand line, but any attempt to change it to ryujinx, starts the ryujinx emulator with "Keys not found" error. I have conformed keys files are in bios/switch.

what am I missing? TIA

**Comment by ordovice** [comment]
The ryujinx emulator requires the keys in a different location.  Ryujinx is not fully supported yet as the Ryujinx team technically doesn't provide the AppImage and it's a very manual process.

From: philsocal ***@***.***>
Sent: Thursday, August 19, 2021 1:34 PM
To: ordovice/batocera-switch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ordovice/batocera-switch] Unable to switch to Ryujinx (#3)


Initially setup for yuzu, but my GPU only supports opengl 4.6+. Attempted to remove yuzu and install Ryujinx (as it supports opengl 4.5), but emulationstation still attempts to start yuzu-
from es_launch_stderr.log-
FileNotFoundError: [Errno 2] No such file or directory: '/userdata/system/switch/yuzu.AppImage'

in switchlauncher.py, it references yuzu on the exitCode = runCommand line, but any attempt to change it to ryujinx, starts the ryujinx emulator with "Keys not found" error. I have conformed keys files are in bios/switch.

what am I missing? TIA

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fordovice%2Fbatocera-switch%2Fissues%2F3&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7Cba8a7f3e8b104514b4d208d963378f91%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637649912551016566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hzavRbVxbly3GMCp0Cqv6EaivEL8%2BGR5T0i3E0ScGXc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGNJTIAJEQUQ635UO5CPMO3T5U6BJANCNFSM5COV5YMA&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7Cba8a7f3e8b104514b4d208d963378f91%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637649912551016566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pYuKzapt9IuS6tHZzMInVjxw7URF9VSEINXEgOFD%2BDc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7Cba8a7f3e8b104514b4d208d963378f91%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637649912551026554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZiAyseld8lnimLhUIXqvHm1BXEHMPy65pb%2Fiv4oEn%2Bg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CDaniel.Walker%40jrautomation.com%7Cba8a7f3e8b104514b4d208d963378f91%7Cffe306ffa9064a7f88ec084628ebd90c%7C1%7C0%7C637649912551026554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4fdomXzQIoe0Rlr6YFiUQt7eTkPA4ZIZic2zHRpVPsA%3D&reserved=0>.
* This email was sent from an external source, please use caution and validate the email before opening attachments or clicking on hyperlinks. *

**Comment by philsocal** [comment]
Understood, thanks for the awesome work (I'll upgrade my GPU to support yuzu)

**Comment by ordovice** [comment]
If you upgraded your GPU, v34 support is now set with autoconfiguration of controls in yuzu.

**Comment by ordovice** [comment]
I've added basic Ryujinx support but it's still not fully setup.  As an FYI

**Comment by ordovice** [comment]
Feel free to test Ryujinx out on the latest version.  Should work for you now on v34 and up

**Comment by ordovice** [comment]
Ryujinx added in v34
